get_app_urls = Xpath("//div[@class='while_apps']//div[@class='item_holder']/a/@href")
categories = Xpath("//div[@class='info']//div[1]//a//text()")
version = Xpath("//div[@class='info']//div[4]/text()")
os = Xpath("//div[@class='info']//div[5]/text()")
internet = Xpath("//div[@class='info']//div[6]/text()")
size = Xpath("//div[@class='info']//div[7]/text()")
raiting = Xpath("//div[@class='info']//div[8]/text()")
russian = Xpath("//div[@class='info']//div[9]/text()")
pkg_name = Xpath("//h1[@itemprop='name']//text()")
img_urls = Xpath("//img/@src")
description = Xpath("//div[@itemprop='description']//text()")
icon = Xpath("//meta[@property='og:image']/@content | //div[@class='c in_holder']/img/@data-src")
download_first_url = Xpath("//a/@href")
download_second_url = Xpath("//a[@id='download_up']/@href")
md5 = Xpath("//div[@class='c']//strong/text()")
app_url = Xpath("//meta[@property='og:type']/@content")
mod_number1 = Xpath("//a[@class='google_play round5']/@href")
mod_number2 = Xpath("//meta[@property='og:image']/@content")
pkg_download_url = Xpath("//div[@class='c']/a[@class='download round30']/@href")
img_urls2 = Xpath("//div[@class='inl']/img/@data-src")